apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  labels:
    app: frontend
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.activePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  labels:
    app: frontend
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.previewPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
