---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    JWT_EXPIRES_IN: {{ .Values.secret.encryptedJwtExpiresIn }}
    JWT_SECRET: {{ .Values.secret.encryptedJwtSecret }}
    MONGO_CATALOG_URI: {{ .Values.secret.encryptedMongoCatalogUri }}
    MONGO_INVENTORY_URI: {{ .Values.secret.encryptedMongoInventoryUri }}
    MONGO_ROOT_PASSWORD: {{ .Values.secret.encryptedMongoRootPassword }}
    MONGO_ROOT_USERNAME: {{ .Values.secret.encryptedMongoRootUsername }}
    MONGO_USER_URI: {{ .Values.secret.encryptedMongoUserUri }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.secret.name }}
      namespace: {{ .Values.namespace }}
