apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rxpulse-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  generators:
    - list:
        elements:
          - chart: infra/base
            name: rxpulse-base-prod
          - chart: infra/sealed-secrets
            name: rxpulse-secrets-prod
          - chart: infra/mongodb
            name: rxpulse-mongodb-prod
          - chart: infra/gateway
            name: rxpulse-gateway-prod
          - chart: charts/user
            name: rxpulse-user-prod
          - chart: charts/catalog
            name: rxpulse-catalog-prod
          - chart: charts/inventory
            name: rxpulse-inventory-prod

  template:
    metadata:
      name: "{{ '{{' }} .name {{ '}}' }}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: rxpulse
        environment: prod
    spec:
      project: rxpulse

      source:
        repoURL: https://github.com/KONDOJUVINAYKUMAR08/rxpulse-helm.git
        targetRevision: main
        path: "{{ '{{' }} .chart {{ '}}' }}"
        helm:
          valueFiles:
            - ../../environments/values-prod.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: rxpulse-prod

      syncPolicy:
        automated: null
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
