{{- if .Values.seedJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-seed-job
  labels:
    app: catalog-seed
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
    "argocd.argoproj.io/sync-wave": "2"
spec:
  backoffLimit: {{ .Values.seedJob.backoffLimit }}
  template:
    metadata:
      labels:
        app: catalog-seed
    spec:
      restartPolicy: OnFailure
      containers:
        - name: catalog-seed
          image: "{{ .Values.image.repository }}:{{ .Values.global.services.catalog.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "src/seed.js"]
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MONGO_CATALOG_URI
{{- end }}
