
global:
  namespace: rxpulse-dev
  environment: dev
catalog:
  replicaCount: 1
  image:
    tag: develop-95d2f22a
  seedJob:
    enabled: true
inventory:
  replicaCount: 1
  image:
    tag: develop-34a02ff4
  seedJob:
    enabled: true
user:
  replicaCount: 1
  image:
    tag: develop-57c08004
frontend:
  replicaCount: 2
  image:
    tag: develop-864985ef
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
base:
  namespace: rxpulse-dev
  configMap:
    nodeEnv: development
mongodb:
  createStorageClass: true
  storage: 5Gi
  storageClass: nfs-client
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
